## Dependencies
highlighter: rouge
markdown: kramdown

# Permalinks
permalink: pretty

#Site
title: Rahim Jiwa
url: rkjiwa.github.io
description: 'Hey. I'm Rahim and this is my blog. Here I'll write about a bunch of things that I am curious about or am interested in. Thanks for checking it out.'
author: Rahim Jiwa
url: https://twitter.com/rkjiwa

paginate: 5
