## Dependencies
highlighter: rouge
markdown: kramdown

# Permalinks
permalink: pretty

#Site
title: Rahim Jiwa
url: rkjiwa.github.io
description: 'Hey. I am Rahim and this is my blog. Here I will write about a bunch of things that I am curious about or am interested in. My opinions are based on the information I had available when forming them and may change. Thanks for checking it out.'
author: Rahim Jiwa
url: https://twitter.com/rkjiwa

paginate: 5

# google analytics
gtag('config', 'UA-103783436-1');



