## Dependencies
pygments: true
markdown: kramdown

# Permalinks
permalink: pretty

#Site
title: Rahim Jiwa
url: rkjiwa.github.io
description: 'Rahim Jiwa is a creative business professional with a passion for solving challenging business problems. His interests include: business (finance, marketing, strategy, economics, and entrepreneurship), science, technology, media, and sports. He also enjoys writing about his interests and long walks on the beach. You can read some of his work here, or contact him below.'

author: Rahim Jiwa
url: https://twitter.com/rkjiwa

paginate: 5
