## Dependencies
pygments: true
markdown: redcarpet

# Permalinks
permalink: pretty

#Site
title: Rahim Jiwa
url: rkjiwa.github.io
#description: 'A curious mind in a complicated world.'

author: Rahim Jiwa
url: https://twitter.com/rkjiwa

paginate: 5
