pygments: true
github: {
    "versions": {
        "jekyll": "1.5.1",
        "kramdown": "1.3.1",
        "liquid": "2.5.5",
        "maruku": "0.7.0",
        "rdiscount": "2.1.7",
        "redcarpet": "2.3.0",
        "RedCloth": "4.2.9",
        "jemoji": "0.1.0",
        "jekyll-mentions": "0.0.6",
        "jekyll-redirect-from": "0.3.1",
        "jekyll-sitemap": "0.2.0",
        "github-pages": "18",
        "ruby": "2.1.1"
    },
    "hostname": "github.com",
    "pages_hostname": "github.io",
    "api_url": "https://api.github.com",
    "environment": "dotcom",
    "public_repositories": rkjiwa.github.io,
    "organization_members": rkjiwa,
    "build_revision": "cbd866ebf142088896cbe71422b949de7f864bce",
    "project_title": "rkjiwa.github.io",
    "project_tagline": "A GitHub Pages site to showcase rkjiwa.gituhb.io",
    "owner_name": "rkjiwa",
    "owner_url": "https://github.com/rkjiwa",
    "owner_gravatar_url": "https://github.com/github.png",
    "repository_url": "https://github.com/rkjiwa/rkjiwa.github.io",
    "repository_nwo": "rkjiwa/rkjiwa.github.io",
    "repository_name": "rkjiwa.github,io",
    "zip_url": "https://github.com/rkjiwa/rkjiwa.github.io/zipball/gh-pages",
    "tar_url": "https://github.com/rkjiwa/rkjiwa.github.io/tarball/gh-pages",
    "clone_url": "https://github.com/rkjiwa/rkjiwa.github.io.git",
    "releases_url": "https://github.com/rkjiwa/rkjiwa.github.io/releases",
    "issues_url": "https://github.com/rkjiwa/rkjiwa.github.io/issues",
    "wiki_url": "https://github.com/rkjiwa/rkjiwa.github.io/wiki",
    "language": null,
    "is_user_page": false,
    "is_project_page": true,
    "show_downloads": true,
    "url": "http://rkjiwa.github.io/", // (or the CNAME)
    "contributors": rkjiwa,
}